### ISSUE TITLE
player is invulnerable

### ISSUE THREAD

**Issue by CrazyAmphibian** [SiriMoel/pharmacokinetics#1]
## description
the player is invulnerable to all forms of damage, including but not limited to: status effects, midas, projectiles, and melee

## expected behavior
i take damage

## what happened
i didn't take damage

## steps to reproduce
load the game up and do something that would have you take damage while having this mod enabled

![noita-20241128-020059-1014415056-00003328](https://github.com/user-attachments/assets/781cf580-3b88-4919-aa77-9af2a7790eba)

**Comment by SiriMoel** [comment]
I cannot seem to recreate this but I will continue to look into it - what other mods do you have enabled?

**Comment by CrazyAmphibian** [comment]
i disabled all other mods before submitting the issue

**Comment by CrazyAmphibian** [comment]
opened in dev executable for more debugging


getting the following errors upon loading a world:
```
Mod enabled: pharmacokinetics 3373139694
Error loading lua script - file doesn't exist: mods/pharmacokinetics/files/scripts/utils.lua
Error loading lua script - file doesn't exist: mods/pharmacokinetics/files/scripts/pharma.lua  
```

and dumping some acid on myself
```
Error loading lua script - file doesn't exist: mods/souls/files/scripts/utils.lua
Error loading lua script - file doesn't exist: mods/souls/files/scripts/souls.lua
Lua error - [string "mods/pharmacokinetics/files/scripts/player_da..."]:6: attempt to call global 'HeldItem' (a nil value)                                                                                                                        Stack traceback:
[string "mods/pharmacokinetics/files/scripts/player_da..."]:6: in function <[string "mods/pharmacokinetics/files/scripts/player_da..."]:4> 
```

maybe you forgot to commit local files to the repo?

**Comment by CrazyAmphibian** [comment]
aha!

you're calling the wrong mod directory, \@files/scripts/player_damage_handler.lua:1
so users without the `souls` mod enabled won't see this bug.
```
dofile_once("mods/souls/files/scripts/utils.lua")
dofile_once("mods/souls/files/scripts/souls.lua")
```

**Comment by SiriMoel** [comment]
bit of a moldos moment, mb - will be fixed now

**Comment by SiriMoel** [comment]
fix pushed to workshop

**Comment by CrazyAmphibian** [comment]
![881100_963](https://github.com/user-attachments/assets/29a50e9d-b717-4a3f-a420-440f5f42eb71)
